url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Andrew and Yuchi photography
email: lyra.love.guo@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Andrew
  pic: andrew_linkedin
  social:
    - title: instagram
      url: https://www.instagram.com/andrewnyuchicamera/



- name: Yuchi
  pic: yuchi_linkedin
  social:
    - title: instagram
      url: https://www.instagram.com/andrewnyuchicamera/


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/andrewnyuchicamera/ 

# Postal address (add as many lines as necessary)
address:
  - line: CB2 8PH

# Build settings
markdown: kramdown
permalink: pretty